name: 'CI'
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  tfsec:
    name: 'Terraform security check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform security scan'
        uses: aquasecurity/tfsec-action@v1.0.0

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: s3_bucket_creation
    needs: tfsec
    env:
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve

      - name: 'Terraform destroy'
        run: terraform destroy -auto-approve
